name: Deploy to production

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14.17]
    steps:
      - uses: actions/checkout@v2

      - name: Set relase version
        run: |
          echo "SENTRY_RELEASE=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Upload sourcemaps
        run: |
          npm install
          npm run build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ENABLED: ${{ secrets.SENTRY_ENABLED }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_RELEASE: ${{ env.SENTRY_RELEASE }}

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ secrets.HEROKU_APP }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
        env:
          HD_BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
          HD_BINANCE_API_SECRET: ${{ secrets.BINANCE_API_SECRET }}
          HD_BINANCE_TESTNET_ENABLED: false
          HD_DB_URL: ${{ secrets.DB_URL }}
          HD_JWT_SECRET: $${{ secrets.JWT_SECRET }}
          HD_NODE_ENV: production
          HD_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          HD_SENTRY_ENABLED: true
          HD_SENTRY_RELEASE: ${{ env.SENTRY_RELEASE }}
